type: object
properties:
  code:
    type: integer
    example: 200
    description: Status code
  message:
    type: string
    example: success
    description: Success or error message
  data:
    type: array
    description: Response data
    items:
      type: object
      properties:
        $ref: ./properties.yaml
  nextPageLink:
    type: string
    example: https://api.bocs.io/dev/products?pageToken=c70e668c
    description: Next page link
